import { Tender, UserProfile } from '../types/tender';

const downloadFile = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

// ==========================================
// 1. SINGLE TENDER EXPORTERS
// ==========================================

export const exportTenderAsJSON = (tender: Tender) => {
  const content = JSON.stringify(tender, null, 2);
  downloadFile(content, `${tender.id}_summary.json`, 'application/json');
};

export const exportTenderAsMarkdown = (tender: Tender) => {
  const s = tender.summary;
  const md = `# Tender Brief: ${tender.title}
**Tender ID:** \`${tender.id}\` | **Reference No:** \`${tender.referenceNo}\`  
**Issuing Authority:** ${tender.organization}  
**Jurisdiction:** ${tender.country} | **Portal:** ${s?.portal || 'e-Tendering Portal'}  
**Category:** ${tender.category}  
**Estimated Net Value:** $${(tender.estimatedValue / 1000000).toFixed(2)}M USD (≈ ৳${((tender.estimatedValue * 122) / 10000000).toFixed(2)} Cr BDT)  
**Lifecycle Stage:** ${tender.stage.replace('_', ' ')} | **Decision Matrix:** ${tender.decision}  
**Submission Cutoff:** ${new Date(tender.submissionDeadline).toLocaleString('en-GB')}  
**Operational Priority:** ${tender.priority} | **Lead Owner:** ${tender.leadOwner.name} (${tender.leadOwner.role})

---

## 1. Executive Summary & Concept
${s?.mainIdea || 'Proposal for enterprise infrastructure modernization and technical support.'}

${s?.classification ? `> **Classification:** \`${s.classification}\`` : ''}

---

## 2. Commercial Requirements & Securities
| Parameter | Value |
| :--- | :--- |
| **Tender Security (EMD)** | ${s?.commercial?.tenderSecurity || 'Bank Guarantee Required'} |
| **Contract / Service Period** | ${s?.commercial?.contractPeriod || '12 Months + 24 Months O&M'} |
| **Tender Document Fee** | ${s?.commercial?.tenderDocPrice || 'Free on Portal'} |
| **Performance Security** | ${s?.commercial?.performanceSecurity || '10% of Contract Value'} |

---

## 3. Technical Requirements
${
  s?.technicalReqs && s.technicalReqs.length > 0
    ? s.technicalReqs.map((r) => `- ${r}`).join('\n')
    : tender.tasks.map((t) => `- ${t.title}`).join('\n')
}

### Software & Technologies Mentioned:
${
  s?.technologyMentioned && s.technologyMentioned.length > 0
    ? s.technologyMentioned.map((t) => `- ${t}`).join('\n')
    : '- Modern Microservices, PostgreSQL, Enterprise Cloud Stack'
}

### Operational & SLA Parameters:
${
  s?.operationalReqs && s.operationalReqs.length > 0
    ? s.operationalReqs.map((o) => `- ${o}`).join('\n')
    : '- 24/7 technical incident resolution and 99.95% system availability.'
}

---

## 4. Key Eligibility & Joint Venture Guidelines
- **General Experience:** ${s?.eligibility?.generalExperience || '5+ years commercial experience'}
- **Similar Experience:** ${s?.eligibility?.similarExperience || 'At least 2 completed contracts of similar complexity'}
- **Minimum Contract Value:** ${s?.eligibility?.similarProjectValue || 'Single contract benchmark'}
- **Annual Turnover:** ${s?.eligibility?.avgTurnover || 'Audited turnover average'}
- **Financial Resources:** ${s?.eligibility?.financialResources || 'Liquid assets or bank credit line'}
- **Certifications:** ${s?.eligibility?.certification || 'ISO 9001, ISO 27001'}
- **Local Presence:** ${s?.eligibility?.localPresence || 'Local branch or registered support center'}

**Joint Venture (JV) Rules:**
- Participation: ${s?.jv?.participation || 'Allowed per tender instructions'}
- Lead Member: ${s?.jv?.leadMember || 'Must meet majority financial criteria'}
- Member Rules: ${s?.jv?.memberRules || 'Qualifications shared proportionally'}

---

## 5. Personnel & Staffing Mandates
| Position | Min. Qualification | Experience | Qty |
| :--- | :--- | :--- | :---: |
${
  s?.personnel && s.personnel.length > 0
    ? s.personnel.map((p) => `| ${p.position} | ${p.qualification} | ${p.experience} | ${p.qty} |`).join('\n')
    : '| Senior Solutions Architect | B.Sc. in Computer Engineering | 8+ Years | 1 |'
}

---

## 6. Hardware & Appliance Specifications
| Equipment | Functional Purpose |
| :--- | :--- |
${
  s?.hardware && s.hardware.length > 0
    ? s.hardware.map((h) => `| ${h.equipment} | ${h.purpose} |`).join('\n')
    : '| Enterprise Rackmount Servers | Application cluster hypervisors |'
}

---

## 7. Key Risks & Management Highlights
${
  s?.risks && s.risks.length > 0
    ? s.risks.map((r) => `- **[${r.type}]** ${r.text}`).join('\n')
    : '- **[Tender Requirement]** Mandatory bank solvency confirmation.'
}

### Management Notes:
${s?.notes || 'Internal remarks and post-bid debrief notes logged in command center.'}

---
*Generated by TenderTracker Command Center on ${new Date().toLocaleDateString('en-GB')}*
`;

  downloadFile(md, `${tender.id}_summary.md`, 'text/markdown');
};

export const exportTenderAsWord = (tender: Tender) => {
  const s = tender.summary;
  const html = `
<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
<head><meta charset='utf-8'><title>${tender.title}</title>
<style>
  body { font-family: 'Calibri', 'Segoe UI', sans-serif; font-size: 11pt; color: #1E293B; line-height: 1.5; }
  h1 { color: #0F172A; font-size: 20pt; border-bottom: 2px solid #2563EB; padding-bottom: 6px; }
  h2 { color: #1E293B; font-size: 14pt; border-bottom: 1px solid #CBD5E1; padding-bottom: 4px; margin-top: 18pt; }
  h3 { color: #2563EB; font-size: 12pt; margin-top: 12pt; }
  table { width: 100%; border-collapse: collapse; margin-top: 8pt; margin-bottom: 12pt; }
  th { background-color: #F1F5F9; color: #0F172A; font-weight: bold; text-align: left; padding: 6pt; border: 1px solid #CBD5E1; }
  td { padding: 6pt; border: 1px solid #CBD5E1; }
  .badge { background-color: #EFF6FF; color: #1D4ED8; padding: 2pt 6pt; font-weight: bold; border-radius: 3pt; }
  .meta-box { background-color: #F8FAFC; border: 1px solid #E2E8F0; padding: 10pt; margin-bottom: 15pt; }
</style>
</head>
<body>
  <h1>Tender Specification Brief: ${tender.title}</h1>
  <div class="meta-box">
    <p><strong>Tender ID:</strong> ${tender.id} &nbsp;|&nbsp; <strong>Reference:</strong> ${tender.referenceNo}</p>
    <p><strong>Authority / Client:</strong> ${tender.organization} (${tender.country})</p>
    <p><strong>Estimated Value:</strong> $${(tender.estimatedValue / 1000000).toFixed(2)}M USD &nbsp;|&nbsp; <strong>Stage:</strong> ${tender.stage} &nbsp;|&nbsp; <strong>Decision:</strong> ${tender.decision}</p>
    <p><strong>Submission Cutoff:</strong> ${new Date(tender.submissionDeadline).toLocaleString('en-GB')}</p>
    <p><strong>Lead Bid Director:</strong> ${tender.leadOwner.name}</p>
  </div>

  <h2>1. Executive Concept & Scope of Work</h2>
  <p>${s?.mainIdea || 'Proposal for deploying enterprise software systems and cloud infrastructure.'}</p>

  <h2>2. Commercial Securities & Guarantees</h2>
  <table>
    <tr><th>Requirement</th><th>Specification</th></tr>
    <tr><td>Tender Security</td><td>${s?.commercial?.tenderSecurity || 'Bank Guarantee Required'}</td></tr>
    <tr><td>Contract / Service Period</td><td>${s?.commercial?.contractPeriod || '12 Months + 24 Months O&M'}</td></tr>
    <tr><td>Tender Document Price</td><td>${s?.commercial?.tenderDocPrice || 'Free on Portal'}</td></tr>
    <tr><td>Performance Security</td><td>${s?.commercial?.performanceSecurity || '10% of Contract Value'}</td></tr>
  </table>

  <h2>3. Key Eligibility & Qualification Criteria</h2>
  <ul>
    <li><strong>General Experience:</strong> ${s?.eligibility?.generalExperience || '5+ Years'}</li>
    <li><strong>Similar Experience:</strong> ${s?.eligibility?.similarExperience || 'At least 2 similar contracts'}</li>
    <li><strong>Minimum Value:</strong> ${s?.eligibility?.similarProjectValue || 'Single contract benchmark'}</li>
    <li><strong>Annual Turnover:</strong> ${s?.eligibility?.avgTurnover || 'Audited turnover average'}</li>
    <li><strong>Certifications:</strong> ${s?.eligibility?.certification || 'ISO 9001, ISO 27001'}</li>
    <li><strong>Local Presence:</strong> ${s?.eligibility?.localPresence || 'Registered local support branch'}</li>
  </ul>

  <h2>4. Key Personnel Mandates</h2>
  <table>
    <tr><th>Position</th><th>Min. Qualification</th><th>Required Experience</th><th>Qty</th></tr>
    ${
      s?.personnel && s.personnel.length > 0
        ? s.personnel.map((p) => `<tr><td><strong>${p.position}</strong></td><td>${p.qualification}</td><td>${p.experience}</td><td>${p.qty}</td></tr>`).join('')
        : '<tr><td>Solutions Architect</td><td>B.Sc. in Computer Engineering</td><td>8+ Years</td><td>1</td></tr>'
    }
  </table>

  <h2>5. Key Risks & Management Highlights</h2>
  <ul>
    ${
      s?.risks && s.risks.length > 0
        ? s.risks.map((r) => `<li><strong>[${r.type}]</strong> ${r.text}</li>`).join('')
        : '<li>Standard operational risk clearance underway.</li>'
    }
  </ul>

  <p style="margin-top: 30pt; font-size: 9pt; color: #64748B;">
    Document generated by TenderTracker Command Center on ${new Date().toLocaleDateString('en-GB')}.
  </p>
</body>
</html>
`;

  downloadFile(html, `${tender.id}_summary.doc`, 'application/msword');
};

export const exportTenderAsPDF = (tender: Tender) => {
  const s = tender.summary;
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to generate the PDF print preview.');
    return;
  }

  printWindow.document.write(`
<!DOCTYPE html>
<html>
<head>
  <title>${tender.id} - ${tender.title}</title>
  <style>
    body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 10pt; color: #0F172A; padding: 25px; line-height: 1.4; }
    .header { border-bottom: 2px solid #0F172A; padding-bottom: 12px; margin-bottom: 15px; }
    .title { font-size: 18pt; font-weight: bold; margin: 0 0 5px; color: #0F172A; }
    .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; background: #F8FAFC; border: 1px solid #E2E8F0; padding: 12px; border-radius: 6px; margin-bottom: 18px; font-size: 9pt; }
    h2 { font-size: 12pt; border-bottom: 1px solid #CBD5E1; padding-bottom: 4px; margin-top: 15px; color: #1E293B; }
    table { width: 100%; border-collapse: collapse; margin-top: 6px; margin-bottom: 12px; font-size: 8.5pt; }
    th { background: #F1F5F9; border: 1px solid #CBD5E1; padding: 6px; text-align: left; }
    td { border: 1px solid #CBD5E1; padding: 6px; }
    .badge { font-weight: bold; color: #2563EB; }
    @media print {
      body { padding: 0; }
      button { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div style="font-size: 8pt; text-transform: uppercase; letter-spacing: 1px; color: #64748B; font-weight: bold;">
      TenderTracker Command Center &bull; Executive Brief
    </div>
    <div class="title">${tender.title}</div>
    <div style="font-family: monospace; font-size: 9pt; color: #2563EB;">
      Tender ID: ${tender.id} &bull; Ref: ${tender.referenceNo} &bull; Portal: ${s?.portal || 'e-GP / UNGM'}
    </div>
  </div>

  <div class="meta-grid">
    <div><strong>Client:</strong> ${tender.organization}</div>
    <div><strong>Jurisdiction:</strong> ${tender.country}</div>
    <div><strong>Estimated Net Value:</strong> $${(tender.estimatedValue / 1000000).toFixed(2)}M USD (≈ ৳${((tender.estimatedValue * 122) / 10000000).toFixed(2)} Cr BDT)</div>
    <div><strong>Submission Cutoff:</strong> ${new Date(tender.submissionDeadline).toLocaleString('en-GB')}</div>
    <div><strong>Lifecycle Stage:</strong> ${tender.stage}</div>
    <div><strong>Go/No-Go Decision:</strong> ${tender.decision}</div>
  </div>

  <h2>1. Scope Objectives & Concept</h2>
  <p>${s?.mainIdea || 'Enterprise proposal addressing sovereign procurement requirements.'}</p>

  <h2>2. Commercial Terms & Guarantees</h2>
  <table>
    <tr><th>Requirement</th><th>Specification</th></tr>
    <tr><td>Tender Security</td><td>${s?.commercial?.tenderSecurity || 'Bank Guarantee Required'}</td></tr>
    <tr><td>Contract Period</td><td>${s?.commercial?.contractPeriod || '12 Months + 24 Months O&M'}</td></tr>
    <tr><td>Document Price</td><td>${s?.commercial?.tenderDocPrice || 'Free'}</td></tr>
    <tr><td>Performance Security</td><td>${s?.commercial?.performanceSecurity || '10% of Contract Value'}</td></tr>
  </table>

  <h2>3. CV & Personnel Mandates</h2>
  <table>
    <tr><th>Position</th><th>Min. Qualification</th><th>Experience</th><th>Qty</th></tr>
    ${
      s?.personnel && s.personnel.length > 0
        ? s.personnel.map((p) => `<tr><td><strong>${p.position}</strong></td><td>${p.qualification}</td><td>${p.experience}</td><td>${p.qty}</td></tr>`).join('')
        : '<tr><td>Solutions Architect</td><td>B.Sc. in Computer Engineering</td><td>8+ Years</td><td>1</td></tr>'
    }
  </table>

  <h2>4. Key Risks & Points</h2>
  <ul>
    ${
      s?.risks && s.risks.length > 0
        ? s.risks.map((r) => `<li><strong>[${r.type}]</strong> ${r.text}</li>`).join('')
        : '<li>Standard operational risk clearance logged.</li>'
    }
  </ul>

  <script>
    window.onload = function() { window.print(); }
  </script>
</body>
</html>
  `);
  printWindow.document.close();
};

// ==========================================
// 2. PIPELINE REGISTRY EXPORTERS
// ==========================================

export const exportPipelineAsJSON = (tenders: Tender[]) => {
  const content = JSON.stringify(tenders, null, 2);
  downloadFile(content, 'tendertracker_pipeline_export.json', 'application/json');
};

export const exportPipelineAsMarkdown = (tenders: Tender[]) => {
  const totalVal = tenders.reduce((acc, t) => acc + (t.estimatedValue || 0), 0);

  const md = `# TenderTracker Pipeline Registry Export
**Generated:** ${new Date().toLocaleDateString('en-GB')}  
**Total Opportunities:** ${tenders.length} | **Total Value:** $${(totalVal / 1000000).toFixed(2)}M USD (≈ ৳${((totalVal * 122) / 10000000).toFixed(2)} Cr BDT)

---

## Active Tender Opportunities
| ID | Title & Scope of Work (SOW) | Authority | Value (USD) | Stage | Decision | Deadline | Readiness |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :---: |
${tenders
  .map(
    (t) =>
      `| \`${t.id}\` | ${t.title} | ${t.organization} | $${((t.estimatedValue || 0) / 1000000).toFixed(2)}M | ${t.stage} | ${t.decision} | ${t.submissionDeadline ? new Date(t.submissionDeadline).toLocaleDateString('en-GB') : '—'} | ${t.readinessScore || 0}% |`
  )
  .join('\n')}

---
*Report exported from TenderTracker Command Center*
`;

  downloadFile(md, 'tendertracker_pipeline_export.md', 'text/markdown');
};

export const exportPipelineAsWord = (tenders: Tender[]) => {
  const totalVal = tenders.reduce((acc, t) => acc + (t.estimatedValue || 0), 0);

  const html = `
<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
<head><meta charset='utf-8'><title>TenderTracker Pipeline</title>
<style>
  body { font-family: 'Calibri', 'Segoe UI', sans-serif; font-size: 10pt; color: #1E293B; }
  h1 { color: #0F172A; font-size: 18pt; border-bottom: 2px solid #2563EB; }
  table { width: 100%; border-collapse: collapse; margin-top: 10pt; font-size: 9.5pt; }
  th { background-color: #F1F5F9; font-weight: bold; border: 1px solid #CBD5E1; padding: 5pt; text-align: left; }
  td { border: 1px solid #CBD5E1; padding: 5pt; }
</style>
</head>
<body>
  <h1>Tender Pipeline Registry Export</h1>
  <p><strong>Generated Date:</strong> ${new Date().toLocaleDateString('en-GB')} &bull; <strong>Total Opportunities:</strong> ${tenders.length} &bull; <strong>Total Valuation:</strong> $${(totalVal / 1000000).toFixed(2)}M USD</p>
  <table>
    <tr>
      <th>Tender ID</th>
      <th>Title & Scope of Work (SOW)</th>
      <th>Authority</th>
      <th>Value</th>
      <th>Stage</th>
      <th>Decision</th>
      <th>Deadline</th>
      <th>Readiness</th>
    </tr>
    ${tenders
      .map(
        (t) => `
      <tr>
        <td><strong>${t.id}</strong></td>
        <td>${t.title}</td>
        <td>${t.organization}</td>
        <td>$${(t.estimatedValue / 1000000).toFixed(2)}M</td>
        <td>$${((t.estimatedValue || 0) / 1000000).toFixed(2)}M</td>
        <td>${t.stage}</td>
        <td>${t.decision}</td>
        <td>${new Date(t.submissionDeadline).toLocaleDateString('en-GB')}</td>
        <td>${t.readinessScore}%</td>
        <td>${t.submissionDeadline ? new Date(t.submissionDeadline).toLocaleDateString('en-GB') : '—'}</td>
        <td>${t.readinessScore || 0}%</td>
      </tr>`
      )
      .join('')}
  </table>
</body>
</html>
`;

  downloadFile(html, 'tendertracker_pipeline_export.doc', 'application/msword');
};

export const exportPipelineAsPDF = (tenders: Tender[]) => {
  const totalVal = tenders.reduce((acc, t) => acc + (t.estimatedValue || 0), 0);

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to open the PDF preview.');
    return;
  }

  printWindow.document.write(`
<!DOCTYPE html>
<html>
<head>
  <title>TenderTracker Pipeline Registry</title>
  <style>
    body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 9pt; color: #0F172A; padding: 20px; }
    h1 { font-size: 16pt; margin: 0 0 5px; color: #0F172A; }
    .sub { font-size: 9pt; color: #64748B; margin-bottom: 15px; }
    table { width: 100%; border-collapse: collapse; font-size: 8.5pt; margin-top: 10px; }
    th { background: #F1F5F9; border: 1px solid #CBD5E1; padding: 6px; text-align: left; }
    td { border: 1px solid #CBD5E1; padding: 6px; }
    @media print {
      body { padding: 0; }
    }
  </style>
</head>
<body>
  <h1>Tender Pipeline Registry</h1>
  <div class="sub">
    Generated on ${new Date().toLocaleDateString('en-GB')} &bull; ${tenders.length} Opportunities &bull; Total Value: $${(totalVal / 1000000).toFixed(2)}M USD
  </div>
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Authority</th>
        <th>Value</th>
        <th>Stage</th>
        <th>Decision</th>
        <th>Deadline</th>
        <th>Readiness</th>
      </tr>
    </thead>
    <tbody>
      ${tenders
        .map(
          (t) => `
        <tr>
          <td><strong>${t.id}</strong></td>
          <td>${t.title}</td>
          <td>${t.organization}</td>
          <td>$${(t.estimatedValue / 1000000).toFixed(2)}M</td>
          <td>$${((t.estimatedValue || 0) / 1000000).toFixed(2)}M</td>
          <td>${t.stage}</td>
          <td>${t.decision}</td>
          <td>${new Date(t.submissionDeadline).toLocaleDateString('en-GB')}</td>
          <td>${t.readinessScore}%</td>
          <td>${t.submissionDeadline ? new Date(t.submissionDeadline).toLocaleDateString('en-GB') : '—'}</td>
          <td>${t.readinessScore || 0}%</td>
        </tr>`
        )
        .join('')}
    </tbody>
  </table>
  <script>
    window.onload = function() { window.print(); }
  </script>
</body>
</html>
  `);
  printWindow.document.close();
};

// ==========================================
// 3. KEY PERSONNEL DOSSIER EXPORTERS (FORM TECH-1)
// ==========================================

export const exportPersonnelDossierAsPDF = (user: UserProfile) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to open the PDF preview.');
    return;
  }

  const pastAssignments = user.pastAssignments || [];
  const certs = user.certifications || [];
  const education = user.education || [];

  printWindow.document.write(`
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Key Personnel Dossier - ${user.name}</title>
  <style>
    @page {
      size: A4 portrait;
      margin: 14mm 12mm;
    }
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      font-size: 9pt;
      line-height: 1.45;
      color: #0F172A;
      background: #FFFFFF;
      margin: 0;
      padding: 24px;
    }
    .header-banner {
      border-bottom: 2.5px solid #0F172A;
      padding-bottom: 12px;
      margin-bottom: 16px;
    }
    .top-tag {
      font-size: 8pt;
      text-transform: uppercase;
      letter-spacing: 1.2px;
      color: #64748B;
      font-weight: 700;
      margin-bottom: 4px;
    }
    .person-name {
      font-size: 20pt;
      font-weight: 800;
      color: #0F172A;
      margin: 0 0 4px 0;
      letter-spacing: -0.5px;
    }
    .proposed-title {
      font-size: 11pt;
      font-weight: 600;
      color: #2563EB;
      margin: 0;
    }
    .meta-card {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 10px;
      background: #F8FAFC;
      border: 1px solid #E2E8F0;
      border-radius: 6px;
      padding: 12px;
      margin-bottom: 18px;
    }
    .meta-field {
      display: flex;
      flex-direction: column;
    }
    .meta-label {
      font-size: 7.5pt;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: #64748B;
      font-weight: 700;
      margin-bottom: 2px;
    }
    .meta-value {
      font-size: 8.5pt;
      font-weight: 600;
      color: #0F172A;
    }
    h2 {
      font-size: 10.5pt;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.8px;
      color: #0F172A;
      border-bottom: 1.5px solid #CBD5E1;
      padding-bottom: 4px;
      margin: 18px 0 10px 0;
      display: flex;
      justify-content: space-between;
      align-items: baseline;
    }
    .cert-pill {
      display: inline-block;
      background: #EFF6FF;
      color: #1D4ED8;
      border: 1px solid #BFDBFE;
      font-size: 8pt;
      font-weight: 600;
      padding: 3px 8px;
      border-radius: 4px;
      margin: 2px 4px 4px 0;
    }
    .edu-table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 6px;
      font-size: 8.5pt;
    }
    .edu-table th {
      background: #F1F5F9;
      border: 1px solid #CBD5E1;
      padding: 6px 8px;
      text-align: left;
      font-weight: 700;
      color: #334155;
    }
    .edu-table td {
      border: 1px solid #CBD5E1;
      padding: 6px 8px;
      color: #0F172A;
    }
    .assignment-item {
      border: 1px solid #E2E8F0;
      border-left: 3.5px solid #2563EB;
      background: #FFFFFF;
      border-radius: 4px;
      padding: 10px 12px;
      margin-bottom: 10px;
      page-break-inside: avoid;
    }
    .assignment-head {
      display: flex;
      justify-content: space-between;
      align-items: baseline;
      margin-bottom: 4px;
    }
    .assignment-name {
      font-size: 10pt;
      font-weight: 700;
      color: #0F172A;
    }
    .assignment-duration {
      font-size: 8pt;
      font-weight: 600;
      color: #64748B;
      background: #F1F5F9;
      padding: 2px 6px;
      border-radius: 4px;
    }
    .assignment-subhead {
      font-size: 8.5pt;
      color: #475569;
      margin-bottom: 6px;
    }
    .assignment-role {
      font-weight: 700;
      color: #2563EB;
    }
    .assignment-client {
      font-weight: 600;
      color: #0F172A;
    }
    .assignment-desc {
      font-size: 8.5pt;
      color: #334155;
      line-height: 1.4;
      margin-bottom: 6px;
    }
    .tag-pill {
      display: inline-block;
      background: #F8FAFC;
      border: 1px solid #E2E8F0;
      color: #334155;
      padding: 1px 6px;
      border-radius: 3px;
      margin: 1px 3px 1px 0;
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
      font-size: 7.5pt;
    }
    .deliverable-pill {
      display: inline-block;
      background: #F0FDF4;
      border: 1px solid #BBF7D0;
      color: #166534;
      padding: 1px 6px;
      border-radius: 3px;
      margin: 1px 3px 1px 0;
      font-size: 7.5pt;
    }
    .declaration-box {
      margin-top: 24px;
      padding: 12px;
      background: #F8FAFC;
      border: 1px dashed #CBD5E1;
      border-radius: 6px;
      font-size: 8pt;
      color: #475569;
      page-break-inside: avoid;
    }
    .sign-row {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 40px;
      margin-top: 30px;
      padding-top: 10px;
    }
    .sign-line {
      border-top: 1px solid #94A3B8;
      padding-top: 4px;
      font-size: 8pt;
      font-weight: 600;
      color: #0F172A;
    }
    @media print {
      body { padding: 0; }
      @page { margin: 12mm; }
    }
  </style>
</head>
<body>
  <div class="header-banner">
    <div class="top-tag">TenderTracker Command Center &bull; Key Personnel Dossier (Form Tech-1)</div>
    <div class="person-name">${user.name}</div>
    <div class="proposed-title">Proposed Tender Role: ${user.proposedDesignation || user.title}</div>
  </div>

  <div class="meta-card">
    <div class="meta-field">
      <span class="meta-label">Corporate Title</span>
      <span class="meta-value">${user.title}</span>
    </div>
    <div class="meta-field">
      <span class="meta-label">Department</span>
      <span class="meta-value">${user.department || 'Bid Operations & Strategy'}</span>
    </div>
    <div class="meta-field">
      <span class="meta-label">Employment Type</span>
      <span class="meta-value">${user.employmentType || 'PERMANENT'}</span>
    </div>
    <div class="meta-field">
      <span class="meta-label">Email Address</span>
      <span class="meta-value">${user.email}</span>
    </div>
    <div class="meta-field">
      <span class="meta-label">Phone / Contact</span>
      <span class="meta-value">${user.phone || 'N/A'}</span>
    </div>
    <div class="meta-field">
      <span class="meta-label">Station / Location</span>
      <span class="meta-value">${user.location || 'Dhaka, Bangladesh'}</span>
    </div>
  </div>

  <h2>1. Statutory & Professional Certifications</h2>
  <div>
    ${
      certs.length > 0
        ? certs.map((c) => `<span class="cert-pill">&check; ${c}</span>`).join('')
        : '<p style="color: #64748B; font-size: 8.5pt;">No statutory certifications recorded.</p>'
    }
  </div>

  <h2>2. Academic Credentials & Higher Education</h2>
  ${
    education.length > 0
      ? `
    <table class="edu-table">
      <thead>
        <tr>
          <th>Degree / Qualification</th>
          <th>Institution / University</th>
          <th style="width: 110px;">Graduation Year</th>
        </tr>
      </thead>
      <tbody>
        ${education
          .map(
            (e) => `
          <tr>
            <td><strong>${e.degree}</strong></td>
            <td>${e.institution}</td>
            <td>${e.year || 'N/A'}</td>
          </tr>`
          )
          .join('')}
      </tbody>
    </table>`
      : '<p style="color: #64748B; font-size: 8.5pt;">No higher education entries recorded.</p>'
  }

  <h2>
    <span>3. Professional Track Record & Past Project Assignments</span>
    <span style="font-size: 8pt; font-weight: normal; color: #64748B;">Total: ${pastAssignments.length} Verified Projects</span>
  </h2>
  <div>
    ${
      pastAssignments.length > 0
        ? pastAssignments
            .map(
              (a) => `
      <div class="assignment-item">
        <div class="assignment-head">
          <span class="assignment-name">${a.projectName}</span>
          <span class="assignment-duration">${a.duration} ${a.deploymentMonths ? `(${a.deploymentMonths} Mo)` : ''}</span>
        </div>
        <div class="assignment-subhead">
          Role: <span class="assignment-role">${a.role}</span> &bull; Client / Authority: <span class="assignment-client">${a.client}</span>
        </div>
        <div class="assignment-desc">${a.coreResponsibilities}</div>
        <div style="margin-top: 4px;">
          ${(a.keyDeliverables || [])
            .map((d) => `<span class="deliverable-pill">&bull; ${d}</span>`)
            .join('')}
        </div>
        <div style="margin-top: 4px;">
          ${(a.technologiesUsed || [])
            .map((t) => `<span class="tag-pill">${t}</span>`)
            .join('')}
        </div>
      </div>`
            )
            .join('')
        : '<p style="color: #64748B; font-size: 8.5pt;">No past project assignments recorded.</p>'
    }
  </div>

  <div class="declaration-box">
    <strong>Statutory Certification Statement (Multilateral Tech-1 Standard):</strong><br />
    I, the undersigned, certify that to the best of my knowledge and belief, this CV correctly describes myself, my qualifications, and my professional experience. I understand that any willful misstatement described herein may lead to disqualification or dismissal by the procuring entity.
    <div class="sign-row">
      <div class="sign-line">
        Signature of Key Personnel &bull; Date: ${new Date().toLocaleDateString('en-GB')}
      </div>
      <div class="sign-line">
        Authorized Bid Representative &bull; TenderTracker Command Center
      </div>
    </div>
  </div>

  <script>
    window.onload = function() { window.print(); }
  </script>
</body>
</html>
  `);
  printWindow.document.close();
};

export const exportPersonnelDossierAsExcel = (user: UserProfile) => {
  const escapeCSV = (val: unknown): string => {
    if (val === null || val === undefined) return '""';
    const str = String(val);
    return `"${str.replace(/"/g, '""')}"`;
  };

  const rows: string[] = [];

  // Title & Metadata
  rows.push(`${escapeCSV('KEY PERSONNEL DOSSIER & PROFESSIONAL TRACK RECORD')},,,,`);
  rows.push(`${escapeCSV('Generated Date')},${escapeCSV(new Date().toLocaleDateString('en-GB') + ' ' + new Date().toLocaleTimeString('en-GB'))},,,,`);
  rows.push(`,,,,`);

  // Personnel Profile Metadata
  rows.push(`${escapeCSV('1. PERSONNEL PROFILE & STATUTORY DETAILS')},,,,`);
  rows.push(`${escapeCSV('Full Name')},${escapeCSV(user.name)},,,,`);
  rows.push(`${escapeCSV('Proposed Tender Designation')},${escapeCSV(user.proposedDesignation || user.title)},,,,`);
  rows.push(`${escapeCSV('Official Title')},${escapeCSV(user.title)},,,,`);
  rows.push(`${escapeCSV('Department')},${escapeCSV(user.department || 'Bid Operations & Strategy')},,,,`);
  rows.push(`${escapeCSV('Employment Relationship')},${escapeCSV(user.employmentType || 'PERMANENT')},,,,`);
  rows.push(`${escapeCSV('Email Address')},${escapeCSV(user.email)},,,,`);
  rows.push(`${escapeCSV('Contact Phone')},${escapeCSV(user.phone || 'N/A')},,,,`);
  rows.push(`${escapeCSV('Official Station / Location')},${escapeCSV(user.location || 'N/A')},,,,`);
  rows.push(`,,,,`);

  // Certifications
  rows.push(`${escapeCSV('2. PROFESSIONAL CERTIFICATIONS')},,,,`);
  if (user.certifications && user.certifications.length > 0) {
    user.certifications.forEach((cert, idx) => {
      rows.push(`${escapeCSV(`Certification #${idx + 1}`)},${escapeCSV(cert)},,,,`);
    });
  } else {
    rows.push(`${escapeCSV('Certifications')},${escapeCSV('None recorded')},,,,`);
  }
  rows.push(`,,,,`);

  // Education
  rows.push(`${escapeCSV('3. ACADEMIC CREDENTIALS')},,,,`);
  rows.push(`${escapeCSV('Degree')},${escapeCSV('Institution')},${escapeCSV('Graduation Year')},,`);
  if (user.education && user.education.length > 0) {
    user.education.forEach((edu) => {
      rows.push(`${escapeCSV(edu.degree)},${escapeCSV(edu.institution)},${escapeCSV(edu.year || 'N/A')},,`);
    });
  } else {
    rows.push(`${escapeCSV('No academic records recorded')},,,,`);
  }
  rows.push(`,,,,`);

  // Past Project Assignments Ledger
  rows.push(`${escapeCSV('4. PROFESSIONAL TRACK RECORD & PAST PROJECT ASSIGNMENTS')},,,,,,,,`);
  rows.push(
    [
      escapeCSV('Assignment ID'),
      escapeCSV('Project Name'),
      escapeCSV('Client / Authority'),
      escapeCSV('Role in Project'),
      escapeCSV('Duration'),
      escapeCSV('Deployment (Months)'),
      escapeCSV('Key Deliverables'),
      escapeCSV('Technologies & Stack'),
      escapeCSV('Core Responsibilities'),
    ].join(',')
  );

  if (user.pastAssignments && user.pastAssignments.length > 0) {
    user.pastAssignments.forEach((a) => {
      rows.push(
        [
          escapeCSV(a.id),
          escapeCSV(a.projectName),
          escapeCSV(a.client),
          escapeCSV(a.role),
          escapeCSV(a.duration),
          escapeCSV(a.deploymentMonths || ''),
          escapeCSV(a.keyDeliverables.join('; ')),
          escapeCSV(a.technologiesUsed.join(', ')),
          escapeCSV(a.coreResponsibilities),
        ].join(',')
      );
    });
  } else {
    rows.push(`${escapeCSV('No project assignments recorded')},,,,,,,,`);
  }

  // Prepend UTF-8 BOM so Excel opens it with proper character encoding
  const csvContent = '\uFEFF' + rows.join('\r\n');
  const filename = `${user.name.replace(/\s+/g, '_')}_CV_Dossier.csv`;
  downloadFile(csvContent, filename, 'text/csv;charset=utf-8;');
};

export const exportPersonnelDossierAsMarkdown = (user: UserProfile) => {
  const lines = [
    `# KEY PERSONNEL DOSSIER & CV SUMMARY`,
    `**Name:** ${user.name}`,
    `**Proposed Tender Designation:** ${user.proposedDesignation || user.title}`,
    `**Official Title:** ${user.title}`,
    `**Department:** ${user.department || 'Bid Operations & Strategy'}`,
    `**Employment Relationship:** ${user.employmentType || 'PERMANENT'}`,
    `**Contact:** ${user.email} | ${user.phone || 'N/A'} | ${user.location || 'N/A'}`,
    ``,
    `## Professional Certifications`,
    ...(user.certifications || []).map((c) => `- ${c}`),
    ``,
    `## Academic Credentials`,
    ...(user.education || []).map((e) => `- ${e.degree} — ${e.institution} (${e.year || 'N/A'})`),
    ``,
    `## Project Track Record & Past Assignments`,
    ...(user.pastAssignments || []).map(
      (a) =>
        `### ${a.projectName}\n- **Client:** ${a.client}\n- **Role:** ${a.role}\n- **Duration:** ${a.duration} (${a.deploymentMonths || 'N/A'} months)\n- **Deliverables:** ${a.keyDeliverables.join(', ')}\n- **Technologies:** ${a.technologiesUsed.join(', ')}\n- **Responsibilities:** ${a.coreResponsibilities}\n`
    ),
    ``,
    `---`,
    `*Generated by TenderTracker Command Center on ${new Date().toLocaleDateString('en-GB')}*`,
  ];
  const content = lines.join('\n');
  downloadFile(content, `${user.name.replace(/\s+/g, '_')}_CV_Dossier.md`, 'text/markdown');
};

export const exportPersonnelDossierAsJSON = (user: UserProfile) => {
  const content = JSON.stringify(user, null, 2);
  downloadFile(content, `${user.name.replace(/\s+/g, '_')}_profile.json`, 'application/json');
};


